# Generated by Django 4.2.19 on 2025-03-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NLWL Winter League', 'NLWL Winter League'), ('Fintan Goss Cup', 'Fintan Goss Cup'), ('Summer League', 'Summer League'), ('Cup', 'Cup'), ('Friendly', 'Friendly'), ('Tournament', 'Tournament'), ('Training', 'Training')], max_length=120)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposition_team', models.CharField(max_length=250)),
                ('venue', models.CharField(max_length=20)),
                ('match_date', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('line_up', models.JSONField(blank=True, default=list)),
                ('substitutes', models.JSONField(blank=True, default=list)),
                ('is_fixture', models.BooleanField(default=True)),
                ('has_result', models.BooleanField(default=False)),
                ('away_fixture', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.competition')),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Preferred Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Centre Back'), ('LCB', 'Left Centre Back'), ('RCB', 'Right Centre Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CM', 'Center Midfield'), ('CDM', 'Center Defensive Midfield'), ('CAM', 'Center Attacking Midfield'), ('LAM', 'Left Attacking Midfield'), ('RAM', 'Right Attacking Midfield'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('ST', 'Striker'), ('CF', 'Center Forward'), ('LW', 'Left Wing'), ('RW', 'Right Wing')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opposition_score', models.IntegerField()),
                ('team_score', models.IntegerField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution'), ('foul', 'Foul'), ('penalty', 'Penalty'), ('own_goal', 'Own Goal')], max_length=50)),
                ('minute', models.PositiveIntegerField(choices=[(1, "1'"), (2, "2'"), (3, "3'"), (4, "4'"), (5, "5'"), (6, "6'"), (7, "7'"), (8, "8'"), (9, "9'"), (10, "10'"), (11, "11'"), (12, "12'"), (13, "13'"), (14, "14'"), (15, "15'"), (16, "16'"), (17, "17'"), (18, "18'"), (19, "19'"), (20, "20'"), (21, "21'"), (22, "22'"), (23, "23'"), (24, "24'"), (25, "25'"), (26, "26'"), (27, "27'"), (28, "28'"), (29, "29'"), (30, "30'"), (31, "31'"), (32, "32'"), (33, "33'"), (34, "34'"), (35, "35'"), (36, "36'"), (37, "37'"), (38, "38'"), (39, "39'"), (40, "40'"), (41, "41'"), (42, "42'"), (43, "43'"), (44, "44'"), (45, "45'"), (46, "46'"), (47, "47'"), (48, "48'"), (49, "49'"), (50, "50'"), (51, "51'"), (52, "52'"), (53, "53'"), (54, "54'"), (55, "55'"), (56, "56'"), (57, "57'"), (58, "58'"), (59, "59'"), (60, "60'"), (61, "61'"), (62, "62'"), (63, "63'"), (64, "64'"), (65, "65'"), (66, "66'"), (67, "67'"), (68, "68'"), (69, "69'"), (70, "70'"), (71, "71'"), (72, "72'"), (73, "73'"), (74, "74'"), (75, "75'"), (76, "76'"), (77, "77'"), (78, "78'"), (79, "79'"), (80, "80'"), (81, "81'"), (82, "82'"), (83, "83'"), (84, "84'"), (85, "85'"), (86, "86'"), (87, "87'"), (88, "88'"), (89, "89'"), (90, "90'"), (91, "91'"), (92, "92'"), (93, "93'"), (94, "94'"), (95, "95'"), (96, "96'"), (97, "97'"), (98, "98'"), (99, "99'"), (100, "100'"), (101, "101'"), (102, "102'"), (103, "103'"), (104, "104'"), (105, "105'"), (106, "106'"), (107, "107'"), (108, "108'"), (109, "109'"), (110, "110'"), (111, "111'"), (112, "112'"), (113, "113'"), (114, "114'"), (115, "115'"), (116, "116'"), (117, "117'"), (118, "118'"), (119, "119'"), (120, "120'")])),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='personnel.match')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('own_goals', models.PositiveIntegerField(default=0)),
                ('penalties_scored', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='personnel.match')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
