# Generated by Django 4.2.19 on 2025-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_competition_created_at_alter_competition_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchevent',
            options={'ordering': ['minute'], 'verbose_name_plural': 'Match Events'},
        ),
        migrations.AlterModelOptions(
            name='playerstat',
            options={'verbose_name_plural': 'Player Statistics'},
        ),
        migrations.AlterField(
            model_name='match',
            name='away_fixture',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together={('category', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='matchevent',
            unique_together={('match', 'player', 'event_type', 'minute')},
        ),
    ]
