# Generated by Django 4.2.19 on 2025-03-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_player_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Centre Back'), ('LCB', 'Left Centre Back'), ('RCB', 'Right Centre Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CM', 'Center Midfield'), ('CDM', 'Center Defensive Midfield'), ('CAM', 'Center Attacking Midfield'), ('LAM', 'Left Attacking Midfield'), ('RAM', 'Right Attacking Midfield'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('ST', 'Striker'), ('CF', 'Center Forward'), ('LW', 'Left Wing'), ('RW', 'Right Wing')], default='GK', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('first_name', 'last_name')},
        ),
    ]
