# Generated by Django 4.2.19 on 2025-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_alter_matchevent_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='additional_info',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('Goal', 'Goal'), ('Assist', 'Assist'), ('Yellow Card', 'Yellow Card'), ('Red Card', 'Red Card'), ('Substitution', 'Substitution'), ('Foul', 'Foul'), ('Penalty', 'Penalty'), ('Own Goal', 'Own Goal')], max_length=50),
        ),
    ]
