# Generated by Django 4.2.19 on 2025-04-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_alter_matchevent_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('Goal', 'Goal'), ('Assist', 'Assist'), ('Yellow Card', 'Yellow Card'), ('Red Card', 'Red Card'), ('Substitution', 'Substitution'), ('Foul', 'Foul'), ('Penalty', 'Penalty'), ('Own Goal', 'Own Goal'), ('Halftime', 'Halftime'), ('Fulltime', 'Fulltime')], max_length=50),
        ),
    ]
