# Generated by Django 4.2.19 on 2025-04-02 17:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_alter_matchevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='matchevent',
            unique_together={('player', 'event_type', 'minute')},
        ),
    ]
