# Generated by Django 4.2.19 on 2025-04-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_imagecontrol_alter_matchevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
