# Generated by Django 4.2.19 on 2025-04-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_competition_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
